version: '3.7'

networks:
  monitoring:
    external: true
  data-plane:
    external: true


services:
  # collector:
  #   image: ''
  #   restart: always
  #   networks:
  #     - monitoring
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "1"


  proxy:
    image: traefik:maroilles
    restart: always
    # depends_on:
    #   - collector
    networks:
      - monitoring
      - data-plane
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik/traefik.toml
        target: /etc/traefik/traefik.toml
      - type: bind
        source: ./traefik/ssl/
        target: /etc/traefik/ssl/
    command: [
      --configfile=/etc/traefik/traefik.toml
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"