version: '3.7'

networks:
  monitoring:
    external: true
  data-plane:
    external: true


services:
  collector:
    image: jumanjiman/rsyslog
    restart: always
    container_name: log_collector
    networks:
      - monitoring
    ports:
      - target: 514
        published: 514
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
      - target: 1514
        published: 1514
        protocol: tcp
        mode: host
      - target: 1514
        published: 1514
        protocol: udp
        mode: host
    volumes:
      - type: bind
        source: ./rsyslog/rsyslogd.conf
        target: /etc/rsyslogd.conf
      - type: bind
        source: ./rsyslog/queues
        target: /var/run/rsyslog/dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"


  proxy:
    image: traefik:maroilles
    restart: always
    depends_on:
      - collector
    networks:
      - monitoring
      - data-plane
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik/traefik.toml
        target: /etc/traefik/traefik.toml
      - type: bind
        source: ./traefik/ssl/
        target: /etc/traefik/ssl/
    command: [
      --configfile=/etc/traefik/traefik.toml
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"